In [4]:
import requests
import pandas as pd

url = 'https://catalog.goteborg.se/rowstore/dataset/cb541050-487e-4eea-b7b6-640d58f28092'

r = requests.get(url)
df = pd.DataFrame(r.json())

df

,resultCount,offset,limit,queryTime,results
0,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'degree Celsius..."
1,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'percent', 'raw..."
2,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'watt per squar..."
3,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'hectopascal', ..."
4,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'metre per seco..."
5,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'degree [unit o..."
6,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'millimetre per..."
7,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
8,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
9,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
10,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
11,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
12,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
13,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
14,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
15,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
16,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'degree Celsius..."
17,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'percent', 'raw..."
18,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'watt per squar..."
19,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'hectopascal', ..."
20,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'metre per seco..."
21,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'degree [unit o..."
22,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'millimetre per..."
23,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
24,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
25,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
26,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
27,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
28,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
29,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
30,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
31,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
32,34,0,100,3743139,"{'date': '2023-05-22', 'unit': 'microgram per ..."
33,34,0,100,3743139,{'date': ''}